# Profile information
name: Ryan Fonzi
title: Ryan Fonzi
description: > # this means to ignore newlines until "baseurl:"
  Ryan Fonzi's personal website
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "rfonzi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
projectsurl: "/projects"

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: "RFonzi"
linkedin: "ryan-fonzi-9b5039138"

# Contact form
email: "ryan.fonzi@gmail.com"

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /projects/page:num/

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
gems:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
